// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestServer.Data;

#nullable disable

namespace TestServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250923094022_NewChargingStiaton")]
    partial class NewChargingStiaton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestServer.Models.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChargingStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Tầng L1, Vincom Centre Landmark 81, 208 Nguyễn Hữu Cảnh, P.22, Q. Bình Thạnh, TP.HCM",
                            Name = "Trạm Sạc Landmark 81"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Tầng 1, Trung tâm thương mại Vincom Cộng Hòa, 15-17 Cộng Hòa, P.4, Q. Tân Bình, TP.HCM",
                            Name = "Trạm Sạc Cộng Hòa"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Tầng 1, TTTM Vincom Ba Tháng Hai, 3C Đường 3 Tháng 2, P.11, Q.10, TP.HCM",
                            Name = "Trạm Sạc Ba Tháng Hai"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Tầng hầm B3, tòa Léman Luxury, 117 Nguyễn Đình Chiểu, P.6, Quận 3",
                            Name = "Trạm Sạc Léman Luxury Apartments"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Số 130/30G, Nguyễn Văn Lượng, P.10, Quận 6",
                            Name = "Trạm Sạc Huỳnh Hiếu Thiện"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Số 89, Hoàng Quốc Việt, P. Phú Thuận, Quận 7",
                            Name = "Trạm Sạc Sky89"
                        },
                        new
                        {
                            Id = 7,
                            Location = "Hầm B5, số 72 Lê Thánh Tôn, Quận 1",
                            Name = "Trạm Sạc Center Đồng Khởi"
                        });
                });

            modelBuilder.Entity("TestServer.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Nguyễn Xuân Thịnh",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 2,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Nguyễn Hưng Thái",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 3,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Nguyễn Bùi Đăng Khôi",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 4,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Lê Minh Đức",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 5,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Vũ Thế Anh",
                            PhoneNumber = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
