// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestServer.Data;

#nullable disable

namespace TestServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250927131124_ChargingDatabase")]
    partial class ChargingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TestServer.Models.ChargingPoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("ChargingPoints");

                    b.HasData(
                        new
                        {
                            Id = "1.1",
                            StationId = 1
                        },
                        new
                        {
                            Id = "2.1",
                            StationId = 2
                        },
                        new
                        {
                            Id = "3.1",
                            StationId = 3
                        },
                        new
                        {
                            Id = "4.1",
                            StationId = 4
                        },
                        new
                        {
                            Id = "5.1",
                            StationId = 5
                        },
                        new
                        {
                            Id = "6.1",
                            StationId = 6
                        },
                        new
                        {
                            Id = "7.1",
                            StationId = 7
                        });
                });

            modelBuilder.Entity("TestServer.Models.ChargingPort", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<string>("PointId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("PointId");

                    b.ToTable("ChargingPorts");

                    b.HasData(
                        new
                        {
                            Id = "1.1.1",
                            ConnectorId = 1,
                            PointId = "1.1",
                            Power = "7 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "1.1.2",
                            ConnectorId = 2,
                            PointId = "1.1",
                            Power = "50 kW",
                            Status = "InUse"
                        },
                        new
                        {
                            Id = "2.1.1",
                            ConnectorId = 1,
                            PointId = "2.1",
                            Power = "22 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "2.1.2",
                            ConnectorId = 2,
                            PointId = "2.1",
                            Power = ">50 kW",
                            Status = "Faulty"
                        },
                        new
                        {
                            Id = "3.1.1",
                            ConnectorId = 1,
                            PointId = "3.1",
                            Power = "7 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "3.1.2",
                            ConnectorId = 2,
                            PointId = "3.1",
                            Power = "50 kW",
                            Status = "InUse"
                        },
                        new
                        {
                            Id = "4.1.1",
                            ConnectorId = 1,
                            PointId = "4.1",
                            Power = "22 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "4.1.2",
                            ConnectorId = 2,
                            PointId = "4.1",
                            Power = "7 kW",
                            Status = "Faulty"
                        },
                        new
                        {
                            Id = "5.1.1",
                            ConnectorId = 1,
                            PointId = "5.1",
                            Power = "7 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "5.1.2",
                            ConnectorId = 2,
                            PointId = "5.1",
                            Power = "22 kW",
                            Status = "InUse"
                        },
                        new
                        {
                            Id = "6.1.1",
                            ConnectorId = 1,
                            PointId = "6.1",
                            Power = ">50 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "6.1.2",
                            ConnectorId = 2,
                            PointId = "6.1",
                            Power = "22 kW",
                            Status = "InUse"
                        },
                        new
                        {
                            Id = "7.1.1",
                            ConnectorId = 1,
                            PointId = "7.1",
                            Power = "7 kW",
                            Status = "Available"
                        },
                        new
                        {
                            Id = "7.1.2",
                            ConnectorId = 2,
                            PointId = "7.1",
                            Power = "50 kW",
                            Status = "Faulty"
                        });
                });

            modelBuilder.Entity("TestServer.Models.ChargingStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChargingStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "L1 Floor, Vincom Centre Landmark 81, 208 Nguyen Huu Canh Street, Ward 22, Binh Thanh District, Ho Chi Minh City",
                            Name = "Landmark 81 Charging Station"
                        },
                        new
                        {
                            Id = 2,
                            Location = "1st Floor, Vincom Cong Hoa Trade Center, 15-17 Cong Hoa Street, Ward 4, Tan Binh District, Ho Chi Minh City",
                            Name = "Cong Hoa Charging Station"
                        },
                        new
                        {
                            Id = 3,
                            Location = "1st Floor, Vincom Ba Thang Hai Trade Center, 3C 3 Thang 2 Street, Ward 11, District 10, Ho Chi Minh City",
                            Name = "Ba Thang Hai Charging Station"
                        },
                        new
                        {
                            Id = 4,
                            Location = "B3 Basement, Leman Luxury Building, 117 Nguyen Dinh Chieu Street, Ward 6, District 3, Ho Chi Minh City",
                            Name = "Leman Luxury Apartments Station"
                        },
                        new
                        {
                            Id = 5,
                            Location = "130/30G Nguyen Van Luong Street, Ward 10, District 6, Ho Chi Minh City",
                            Name = "Huynh Hieu Thien Station"
                        },
                        new
                        {
                            Id = 6,
                            Location = "89 Hoang Quoc Viet Street, Phu Thuan Ward, District 7, Ho Chi Minh City",
                            Name = "Sky89 Station"
                        },
                        new
                        {
                            Id = 7,
                            Location = "B5 Basement, 72 Le Thanh Ton Street, District 1, Ho Chi Minh City",
                            Name = "Center Dong Khoi Station"
                        });
                });

            modelBuilder.Entity("TestServer.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Nguyễn Xuân Thịnh",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 2,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Nguyễn Hưng Thái",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 3,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Nguyễn Bùi Đăng Khôi",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 4,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Lê Minh Đức",
                            PhoneNumber = ""
                        },
                        new
                        {
                            Id = 5,
                            Car = "",
                            LicenseNumber = "",
                            Name = "Vũ Thế Anh",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("TestServer.Package.Connector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Connectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CCS (DC)"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CHAdeMO (DC)"
                        });
                });

            modelBuilder.Entity("TestServer.Package.PowerRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PowerRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Range = "0-7"
                        },
                        new
                        {
                            Id = 2,
                            Range = "7-50"
                        },
                        new
                        {
                            Id = 3,
                            Range = ">50"
                        });
                });

            modelBuilder.Entity("TestServer.Package.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConnectorId")
                        .HasColumnType("int");

                    b.Property<int>("PowerRangeId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("TimeRangeId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectorId");

                    b.HasIndex("PowerRangeId");

                    b.HasIndex("TimeRangeId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("PriceLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectorId = 1,
                            PowerRangeId = 1,
                            Price = 3500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ConnectorId = 1,
                            PowerRangeId = 1,
                            Price = 4500.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            ConnectorId = 1,
                            PowerRangeId = 1,
                            Price = 3000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            ConnectorId = 1,
                            PowerRangeId = 2,
                            Price = 4000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            ConnectorId = 1,
                            PowerRangeId = 2,
                            Price = 5500.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            ConnectorId = 1,
                            PowerRangeId = 2,
                            Price = 3500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            ConnectorId = 1,
                            PowerRangeId = 3,
                            Price = 5500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            ConnectorId = 1,
                            PowerRangeId = 3,
                            Price = 7000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            ConnectorId = 1,
                            PowerRangeId = 3,
                            Price = 4500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            ConnectorId = 2,
                            PowerRangeId = 1,
                            Price = 4500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            ConnectorId = 2,
                            PowerRangeId = 1,
                            Price = 6000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            ConnectorId = 2,
                            PowerRangeId = 1,
                            Price = 4000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            ConnectorId = 2,
                            PowerRangeId = 2,
                            Price = 6000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            ConnectorId = 2,
                            PowerRangeId = 2,
                            Price = 7500.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            ConnectorId = 2,
                            PowerRangeId = 2,
                            Price = 5000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            ConnectorId = 2,
                            PowerRangeId = 3,
                            Price = 7000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            ConnectorId = 2,
                            PowerRangeId = 3,
                            Price = 9000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            ConnectorId = 2,
                            PowerRangeId = 3,
                            Price = 6000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            ConnectorId = 3,
                            PowerRangeId = 1,
                            Price = 4500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 20,
                            ConnectorId = 3,
                            PowerRangeId = 1,
                            Price = 6000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            ConnectorId = 3,
                            PowerRangeId = 1,
                            Price = 4000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            ConnectorId = 3,
                            PowerRangeId = 2,
                            Price = 6000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 23,
                            ConnectorId = 3,
                            PowerRangeId = 2,
                            Price = 7500.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 24,
                            ConnectorId = 3,
                            PowerRangeId = 2,
                            Price = 5000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 25,
                            ConnectorId = 3,
                            PowerRangeId = 3,
                            Price = 7000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            ConnectorId = 3,
                            PowerRangeId = 3,
                            Price = 9000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 27,
                            ConnectorId = 3,
                            PowerRangeId = 3,
                            Price = 6000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 1
                        },
                        new
                        {
                            Id = 28,
                            ConnectorId = 1,
                            PowerRangeId = 1,
                            Price = 4500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 29,
                            ConnectorId = 1,
                            PowerRangeId = 1,
                            Price = 6000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 30,
                            ConnectorId = 1,
                            PowerRangeId = 1,
                            Price = 4000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 31,
                            ConnectorId = 1,
                            PowerRangeId = 2,
                            Price = 5500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 32,
                            ConnectorId = 1,
                            PowerRangeId = 2,
                            Price = 7000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 33,
                            ConnectorId = 1,
                            PowerRangeId = 2,
                            Price = 4500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 34,
                            ConnectorId = 1,
                            PowerRangeId = 3,
                            Price = 6500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 35,
                            ConnectorId = 1,
                            PowerRangeId = 3,
                            Price = 8000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 36,
                            ConnectorId = 1,
                            PowerRangeId = 3,
                            Price = 5500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 37,
                            ConnectorId = 2,
                            PowerRangeId = 1,
                            Price = 5500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 38,
                            ConnectorId = 2,
                            PowerRangeId = 1,
                            Price = 7000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 39,
                            ConnectorId = 2,
                            PowerRangeId = 1,
                            Price = 5000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 40,
                            ConnectorId = 2,
                            PowerRangeId = 2,
                            Price = 7000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 41,
                            ConnectorId = 2,
                            PowerRangeId = 2,
                            Price = 9000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 42,
                            ConnectorId = 2,
                            PowerRangeId = 2,
                            Price = 6500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 43,
                            ConnectorId = 2,
                            PowerRangeId = 3,
                            Price = 8500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 44,
                            ConnectorId = 2,
                            PowerRangeId = 3,
                            Price = 10500.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 45,
                            ConnectorId = 2,
                            PowerRangeId = 3,
                            Price = 7500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 46,
                            ConnectorId = 3,
                            PowerRangeId = 1,
                            Price = 5500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 47,
                            ConnectorId = 3,
                            PowerRangeId = 1,
                            Price = 7000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 48,
                            ConnectorId = 3,
                            PowerRangeId = 1,
                            Price = 5000.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 49,
                            ConnectorId = 3,
                            PowerRangeId = 2,
                            Price = 7000.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 50,
                            ConnectorId = 3,
                            PowerRangeId = 2,
                            Price = 9000.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 51,
                            ConnectorId = 3,
                            PowerRangeId = 2,
                            Price = 6500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 52,
                            ConnectorId = 3,
                            PowerRangeId = 3,
                            Price = 8500.0,
                            TimeRangeId = 1,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 53,
                            ConnectorId = 3,
                            PowerRangeId = 3,
                            Price = 10500.0,
                            TimeRangeId = 2,
                            VehicleTypeId = 2
                        },
                        new
                        {
                            Id = 54,
                            ConnectorId = 3,
                            PowerRangeId = 3,
                            Price = 7500.0,
                            TimeRangeId = 3,
                            VehicleTypeId = 2
                        });
                });

            modelBuilder.Entity("TestServer.Package.TimeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TimeRanges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Range = "06:01–17:00"
                        },
                        new
                        {
                            Id = 2,
                            Range = "17:01–21:00"
                        },
                        new
                        {
                            Id = 3,
                            Range = "21:01–06:00"
                        });
                });

            modelBuilder.Entity("TestServer.Package.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Motorbike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Car"
                        });
                });

            modelBuilder.Entity("TestServer.Models.ChargingPoint", b =>
                {
                    b.HasOne("TestServer.Models.ChargingStation", "ChargingStation")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingStation");
                });

            modelBuilder.Entity("TestServer.Models.ChargingPort", b =>
                {
                    b.HasOne("TestServer.Package.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestServer.Models.ChargingPoint", "ChargingPoint")
                        .WithMany("ChargingPorts")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingPoint");

                    b.Navigation("Connector");
                });

            modelBuilder.Entity("TestServer.Package.PriceList", b =>
                {
                    b.HasOne("TestServer.Package.Connector", "Connector")
                        .WithMany()
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestServer.Package.PowerRange", "PowerRange")
                        .WithMany()
                        .HasForeignKey("PowerRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestServer.Package.TimeRange", "TimeRange")
                        .WithMany()
                        .HasForeignKey("TimeRangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestServer.Package.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connector");

                    b.Navigation("PowerRange");

                    b.Navigation("TimeRange");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("TestServer.Models.ChargingPoint", b =>
                {
                    b.Navigation("ChargingPorts");
                });
#pragma warning restore 612, 618
        }
    }
}
